### ISSUE TITLE
Learnable

### ISSUE THREAD

**Issue by SchwinnL** [haidark/WaveletDeconv#1]
The weights of the neural network layer are not learnable but fixed.
I had to add "self.add_weight(...)", to make the network learn the scales. 
Is this intentional?

**Comment by haidark** [comment]
This was not the behavior I saw during testing. What version of Keras/Tensorflow are your running? This could be a result of an API change.

**Comment by SchwinnL** [comment]
I'm running the latest version. 
"self.trainable_weights = [self.W]" This line is maybe outdated.
I trained the network for a speaker recognition task on the timit data set for some time, but the weights didn't change.  After adding "self.add_weight(...)" it worked.
