### ISSUE TITLE
Support for TF2 and tf.keras?

### ISSUE THREAD

**Issue by vlawhern** [haidark/WaveletDeconv#2]
Hi,

I came across this package and found it pretty interesting. I was wondering if you were planning support for TF2, specifically with tf.keras. I was able to get this to work with regular Keras but was unable to with tf.keras.

**Comment by haidark** [comment]
Hi, thanks for finding this! Sorry, no plans to build support for TF2 and tf.keras but you are welcome to make a pull request :)
